server: 
  port: 80
  servlet:
    context-path: /
spring: 
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_student
      username: root
      password: 123456
   jpa: 
      hibernate:
        ddl-auto: update
      show-sql: true
   thymeleaf:
       cache: false
   mvc:
    view:
      prefix: /templates/,/webapp/admin/
      suffix: .html
imageFilePath: D://eclipse-workspace-2019-8/ClubTest/src/main/webapp/static/newsImage/  
 
